name: Connect to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    
    steps:

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: upgrade
      run: az extension update --name ssh
      
    - name: Azure Login
      run: az login -u "hossein.hajjari@klm.com" -p "Tebyan@20100000"
