name: Connect to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: azure/login@v1
      with:
        creds: '{"subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}", "clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'
        environment: azurecloud
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL
        allow-no-subscriptions: true
        enable-AzPSSession: true
