name: Connect to Azure

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:

    - name: Debug Azure CLI
      run: |
        echo "Azure SP Credentials:"
        echo "Client Secret: ${{ secrets.AZURE_CLIENT_SECRET }}"
        echo "Client ID: ${{ secrets.AZURE_CLIENT_ID }}"
        echo "Tenant ID: ${{ secrets.AZURE_TENANT_ID }}"
        echo "Subscription ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  
