name: Run tests on Java 17

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run unit tests on Java 17
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build and package project
        run: mvn -f pom.xml package