
name: Build and deploy CourseMe

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Docker Image Tag' 
        required: true                  
        default: 'latest'               

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action  
        uses: buildpacks/github-actions/setup-pack@v4.8.1  

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build app with pack CLI & publish to GitHub Container Registry  
        run: |  
          pack build ${{ secrets.DOCKERHUB_USERNAME }}/courseme:${{ github.event.inputs.tag_name }} --builder paketobuildpacks/builder:tiny --path . --env "BP_JVM_VERSION=17" --publish
