# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy CourseMe

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Docker Image Tag'  # Description for the input
        required: true                  # Whether the input is required or optional
        default: 'latest'               # Default value

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v4

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action  
        uses: buildpacks/github-actions/setup-pack@v4.8.1  
  

      - name: Build app with pack CLI & publish to GitHub Container Registry  
        run: |  
          pack build coursemeimg --builder paketobuildpacks/builder:tiny --path . --env "BP_JVM_VERSION=17"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Pack CLI
        run: |
          wget https://github.com/buildpacks/pack/releases/download/v0.22.0/pack-v0.22.0-linux.tgz
          tar xvf pack-v0.22.0-linux.tgz
          sudo mv pack /usr/local/bin

      - name: Echo Image Name
        run: echo ${{ secrets.DOCKERHUB_USERNAME }}/courseme:${{ github.event.inputs.image_tag }}

      - name: Build container image using Paketo Buildpacks
        run: pack build courseme --builder paketobuildpacks/builder:base

      # - name: Push Docker image to Docker Hub
      #   run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/courseme:${{ github.event.inputs.image_tag }}
